### ISSUE TITLE
Issue 24383: Statistics are lost when reloading a Multiplayer Game In Mulitplayer

### ISSUE THREAD

**Issue by binarycoder** [TakingInitiative/wesnoth#16]
https://gna.org/bugs/?24383

When a multiplayer game save (either auto or manual) is made and then reloaded through the multiplayer pathway, the statistics are lost. However if the game is loaded through the single-player pathway the statistics are shown to still be present. 
Can be reproduced by creating a multiplayer local game against the computer, recruiting a few units, saving the game, then reloading it. The recruit statistics will be back to zero if the multiplayer pathway is used.

**Comment by qmo2015** [comment]
Located in wesnoth\src\game_initialization\multiplayer.cpp line 407.
A function call ( statistics::fresh_stats(); ) on line 407 sets all statistics back to default, causing the bug.
Fixed by removing line 407.
