### ISSUE TITLE
Issue 25522: bad terrain transition

### ISSUE THREAD

**Issue by binarycoder** [TakingInitiative/wesnoth#6]
wesnoth v1.13.6+dev (9359a91-Clean) 
As seen on arcanclave citadel. 
Screenshot attached

**Comment by qmo2015** [comment]
Fixed by Lari Nieminen <zookeeper>.
https://gna.org/bugs/index.php?25522

**Comment by qmo2015** [comment]
Fixed by Lari Nieminen "zookeeper".
https://gna.org/bugs/index.php?25522
